schema_version: 1

context:
  name: pylammpsmpi
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pylammpsmpi-${{ version }}.tar.gz
  sha256: 39baa15f9527c2bdea3610a836c93e58f883825b3723b88aad4e49f959b08fee

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - executorlib
    - mpi4py
    - numpy
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - mpi4py >=4.1.2,<=4.1.2
    - executorlib >=1.9.0,<=1.9.3
    - numpy >=2.4.6,<=2.4.6
tests:
  - python:
      imports:
        - pylammpsmpi
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pylammpsmpi

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
